In [1]:
import numpy as np

vector_1d = np.arange(1, 11)
print("Одновимірний масив з першими 10-ма натуральними числами:")
print(vector_1d)

matrix_3x3_zeros = np.zeros((3, 3), dtype=int)
print("\nДвовимірний масив 3x3 заповнений нулями:")
print(matrix_3x3_zeros)

matrix_5x5_random_ints = np.random.randint(1, 11, size=(5, 5))
print("\nМасив 5x5 заповнений випадковими цілими числами від 1 до 10:")
print(matrix_5x5_random_ints)

matrix_4x4_random_floats = np.random.rand(4, 4)
print("\nМасив 4x4 заповнений випадковими дійсними числами від 0 до 1:")
print(matrix_4x4_random_floats)

array_5_a = np.random.randint(1, 11, size=5)
array_5_b = np.random.randint(1, 11, size=5)
print("\nПерший одновимірний масив:")
print(array_5_a)
print("Другий одновимірний масив:")
print(array_5_b)
print("Поелементне додавання:")
print(array_5_a + array_5_b)
print("Поелементне віднімання:")
print(array_5_a - array_5_b)
print("Поелементне множення:")
print(array_5_a * array_5_b)

vector_7_a = np.random.rand(7)
vector_7_b = np.random.rand(7)
print("\nПерший вектор розміром 7:")
print(vector_7_a)
print("Другий вектор розміром 7:")
print(vector_7_b)
print("Скалярний добуток:")
print(np.dot(vector_7_a, vector_7_b))

matrix_2x2 = np.random.randint(1, 11, size=(2, 2))
matrix_2x3 = np.random.randint(1, 11, size=(2, 3))
print("\nМатриця 2x2:")
print(matrix_2x2)
print("Матриця 2x3:")
print(matrix_2x3)
print("Добуток матриць 2x2 і 2x3:")
print(np.dot(matrix_2x2, matrix_2x3))

matrix_3x3 = np.random.randint(1, 11, size=(3, 3))
print("\nМатриця 3x3:")
print(matrix_3x3)
try:
    matrix_3x3_inv = np.linalg.inv(matrix_3x3)
    print("Обернена матриця 3x3:")
    print(matrix_3x3_inv)
except np.linalg.LinAlgError:
    print("Матриця є виродженою, обернена матриця не існує.")

matrix_4x4 = np.random.rand(4, 4)
print("\nМатриця 4x4:")
print(matrix_4x4)
print("Транспонована матриця 4x4:")
print(matrix_4x4.T)

matrix_3x4 = np.random.randint(1, 11, size=(3, 4))
vector_4 = np.random.randint(1, 11, size=4)
print("\nМатриця 3x4:")
print(matrix_3x4)
print("Вектор розміром 4:")
print(vector_4)
print("Результат перемноження матриці на вектор:")
print(np.dot(matrix_3x4, vector_4))

matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.rand(3)
print("\nМатриця 2x3:")
print(matrix_2x3)
print("Вектор розміром 3:")
print(vector_3)
print("Результат перемноження матриці на вектор:")
print(np.dot(matrix_2x3, vector_3))

matrix_2x2_a = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_b = np.random.randint(1, 11, size=(2, 2))
print("\nПерша матриця 2x2:")
print(matrix_2x2_a)
print("Друга матриця 2x2:")
print(matrix_2x2_b)
print("Поелементне множення матриць 2x2:")
print(matrix_2x2_a * matrix_2x2_b)

matrix_2x2_c = np.random.randint(1, 11, size=(2, 2))
matrix_2x2_d = np.random.randint(1, 11, size=(2, 2))
print("\nПерша матриця 2x2:")
print(matrix_2x2_c)
print("Друга матриця 2x2:")
print(matrix_2x2_d)
print("Добуток матриць 2x2:")
print(np.dot(matrix_2x2_c, matrix_2x2_d))

matrix_5x5_random_ints_100 = np.random.randint(1, 101, size=(5, 5))
print("\nМатриця 5x5 заповнена випадковими цілими числами від 1 до 100:")
print(matrix_5x5_random_ints_100)
print("Сума елементів матриці:")
print(np.sum(matrix_5x5_random_ints_100))

matrix_4x4_a = np.random.randint(1, 11, size=(4, 4))
matrix_4x4_b = np.random.randint(1, 11, size=(4, 4))
print("\nПерша матриця 4x4:")
print(matrix_4x4_a)
print("Друга матриця 4x4:")
print(matrix_4x4_b)
print("Різниця матриць 4x4:")
print(matrix_4x4_a - matrix_4x4_b)

matrix_3x3_floats = np.random.rand(3, 3)
print("\nМатриця 3x3 заповнена випадковими дійсними числами від 0 до 1:")
print(matrix_3x3_floats)
print("Вектор-стовпчик сум кожного рядка матриці:")
print(np.sum(matrix_3x3_floats, axis=1))

matrix_3x4_ints = np.random.randint(1, 11, size=(3, 4))
print("\nМатриця 3x4 з довільними цілими числами:")
print(matrix_3x4_ints)
print("Матриця квадратів цих чисел:")
print(np.square(matrix_3x4_ints))

vector_4_ints = np.random.randint(1, 51, size=4)
print("\nВектор розміром 4 з випадковими цілими числами від 1 до 50:")
print(vector_4_ints)
print("Вектор з квадратними коренями цих чисел:")
print(np.sqrt(vector_4_ints))


Одновимірний масив з першими 10-ма натуральними числами:
[ 1  2  3  4  5  6  7  8  9 10]

Двовимірний масив 3x3 заповнений нулями:
[[0 0 0]
 [0 0 0]
 [0 0 0]]

Масив 5x5 заповнений випадковими цілими числами від 1 до 10:
[[ 3  4 10  2  5]
 [ 3  2  3 10  8]
 [ 9  3  8  6  6]
 [ 4  8  7  1  9]
 [ 9  6  5  8  2]]

Масив 4x4 заповнений випадковими дійсними числами від 0 до 1:
[[0.0322767  0.788234   0.63810697 0.44628649]
 [0.96371282 0.90530935 0.55143654 0.46436116]
 [0.0566311  0.3658468  0.89150619 0.89322576]
 [0.15423161 0.94581513 0.53478732 0.36429631]]

Перший одновимірний масив:
[1 1 6 9 3]
Другий одновимірний масив:
[5 3 6 3 7]
Поелементне додавання:
[ 6  4 12 12 10]
Поелементне віднімання:
[-4 -2  0  6 -4]
Поелементне множення:
[ 5  3 36 27 21]

Перший вектор розміром 7:
[0.78703383 0.50064655 0.41871011 0.3391094  0.59386775 0.09561603
 0.85770322]
Другий вектор розміром 7:
[0.12652341 0.11806565 0.73388411 0.3133514  0.86815815 0.69560056
 0.21670398]
Скалярний добуток:
1.340